spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_rntsDB
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

  profiles:
    include: oauth, jwt, ncp

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    username: seyoungkwon29@naver.com
    password: ZQ3B6994RTHX
    host: smtp.naver.com
    port: 465